name: déploiement vers hébergeur
on:
  push:
    branches:
      - ci/deploy
  workflow_dispatch:

jobs:
  deploy:
    name: Déploiement vers hébergeur
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code source
        uses: actions/checkout@v4

      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Installation des dépendances Composer
        run: composer install --optimize-autoloader --no-interaction --no-progress

      - name: Créer .env.local
        run: |
          echo "" > .env.local
          echo "APP_ENV=dev" >> .env.local
          echo "APP_DEBUG=1" >> .env.local
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env.local
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env.local

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.env
            **/README.md
            **/*.bat
            **/*.sh
            **/*.sql
            **/tests/**
            var/cache/dev/**
            sonar-project.properties